import turtle

g = turtle.Turtle()

turtle.shape('turtle')

turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)
turtle.forward(50)
turtle.stamp()
turtle.backward(50)
turtle.left(30)

input()